### ISSUE TITLE
Unable to delete the .juju directory due to permission denied

### ISSUE THREAD

**Issue by geoffmcc** [fsquillace/juju#80]
Hello. First allow me to say although I just started using it today, I am a  big fan of your project.

I came upon a situation where I needed to delete the .juju folder as I am currently trying to set it with a username rather than ihavenoname when using without fake root. When I attempted to delete the .juju directory, I found that everything deleted but ~/.juju/etc/ca-certificates/extracted due to permission problems.

**/.juju/etc/ca-certificates**

**~/.juju/etc/ca-certificates/extracted**
*drwxr-xr-x. 3 xxxx yyyy   4096 Apr 15 20:21 .*
*drwxr-xr-x. 4 xxxx yyyy   4096 Apr  2 16:36 ..*
*-r--r--r--. 1 xxxx yyyy 363354 Apr 15 20:21 ca-bundle.trust.crt* 
*dr-xr-xr-x. 2 xxxx yyyy  20480 Apr 15 20:21 cadir*
*-r--r--r--. 1 xxxx yyyy 224035 Apr 15 20:21 email-ca-bundle.pem*
*-r--r--r--. 1 xxxx yyyy 215629 Apr 15 20:21 objsign-ca-bundle.pem*
*-r--r--r--. 1 xxxx yyyy 272051 Apr 15 20:21 tls-ca-bundle.pem*

**~/.juju/etc/ca-certificates/extracted/cadir**
*4 -r--r--r-- 1 root root  2610 Apr 15 20:21 CAcert_Class_3_Root.pem*
*4 -r--r--r-- 1 root root  2569 Apr 15 20:21 CA_Cert_Signing_Authority.pem*
*4 -r--r--r-- 1 root root  1468 Apr 15 20:21 CA_Disig.pem*
*4 -r--r--r-- 1 root root  1935 Apr 15 20:21 CA_Disig_Root_R1.pem*
*4 -r--r--r-- 1 root root  1935 Apr 15 20:21 CA_Disig_Root_R2.pem*
*4 -r--r--r-- 1 root root  1704 Apr 15 20:21 Camerfirma_Chambers_of_Commerce_Root.pem*
*4 -r--r--r-- 1 root root  1330 Apr 15 20:21 Certigna.pem*
*4 -r--r--r-- 1 root root  2004 Apr 15 20:21 Certinomis_-_Autorit___Racine.pem*
*4 -r--r--r-- 1 root root  1298 Apr 15 20:21 Certplus_Class_2_Primary_CA.pem*
*4 -r--r--r-- 1 root root  1176 Apr 15 20:21 certSIGN_ROOT_CA.pem*
*4 -r--r--r-- 1 root root  1119 Apr 15 20:21 Certum_Root_CA.pem*
*4 -r--r--r-- 1 root root  1354 Apr 15 20:21 Certum_Trusted_Network_CA.pem*

**and many others in that directory**

Could we get those to be drwxr-xr-x or whatever they would need to be in order to allow the deletion of ~/.juju without sudo acces.

If I was to delete /etc/ca-certificates/extracted directory (or possibly just chmod them myself to what they need to be within juju as fakeroot before I delete the .juju directory within /home, would that do the trick? 

When I attempted to delete the .juju directory and found everything deleted but .juju/etc/ca-certificates/extracted I wondered if it would have worked if I had tried those things first, but by then it was too late and I had to have an admin delete the directory for me and I would like to not have to ask again if the situation arises.

**Comment by geoffmcc** [comment]
There is no mention of juju -d in readme, but I still consider this my bad for not checking the /bin/juju source and seeing it there.

Closing issue.

**Comment by philrosenberg** [comment]
I'm adding this because I have had the same issue, but by the time I realised my junest install was no longer their so junest -d obviously wouldn't work.
The problem is caused because the user does not have write permissions on the directory which contains those files From your main Linux install (i.e. not in junest) do 
chmod +w ~/.junest/.junest/.junest/etc/ca-certificates/extracted/cadir
or modify the path if you used a non-standard install location. You should then be able to delete that directory and its contents.
